### ISSUE TITLE
download_images is not defined

### ISSUE THREAD

**Issue by ChristianFJung** [lesscomfortable/google-image-dataset#1]
Any idea why jupyter is telling me download_images is not defined,
I know fastai is running.

**Comment by fpingham** [comment]
You need fastai 1.0.14. Run:

`conda install -c fastai fastai`

and try again.

**Comment by ChristianFJung** [comment]
I’ve updated fastai but juypter can’t find download_images

I’ve noticed when I go to the conda tab, I get this error.

EnvironmentLocationNotFound: Not a conda environment: /home/jupyter/.conda/envs/anaconda3


Any ideas?

**Comment by fpingham** [comment]
Can you try running from you command line:

```bash
source activate fastai
conda install -c fastai fastai
```

Then run from your notebook:
`import fastai`
`fastai.show_install(0)`

This should output 1.0.15

**Comment by ricknta** [comment]
Thanks, that finally worked!  But only after I restarted my VM (on Salamander) .

Rick N.

**Comment by ChristianFJung** [comment]
Thanks so much, I got it. Had to stop my instance on gcloud.
